/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef access_CONSTANTS_H
#define access_CONSTANTS_H

#include "access_types.h"



class accessConstants {
 public:
  accessConstants();

};

extern const accessConstants g_access_constants;



#endif
